# Generated by Django 5.2.7 on 2025-10-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mfa_method',
            field=models.CharField(choices=[('email', 'Código por correo'), ('sms', 'Código por SMS'), ('secq', 'Pregunta de seguridad'), ('totp', 'Aplicación OTP (TOTP)')], default='email', max_length=8),
        ),
    ]
