# Generated by Django 5.2.7 on 2025-11-07 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_mfa_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_method',
            field=models.CharField(blank=True, choices=[('email', 'Correo electrónico'), ('phone', 'Teléfono')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mfa_method',
            field=models.CharField(choices=[('email', 'Código por correo'), ('sms', 'Código por SMS'), ('secq', 'Pregunta de seguridad'), ('totp', 'Aplicación OTP (TOTP)'), ('usb_key', 'Llave USB (YubiKey)')], default='email', max_length=8),
        ),
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_type', models.CharField(choices=[('LOGIN', 'Login'), ('USER_CREATION', 'Creación de usuario'), ('PASSWORD_RESET', 'Reseteo de contraseña'), ('ACCOUNT_UNLOCK', 'Desbloqueo de cuenta')], max_length=32)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_device', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
        migrations.CreateModel(
            name='AccountRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recovery_email', models.EmailField(max_length=254)),
                ('recovery_code', models.CharField(blank=True, max_length=6)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_recoveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlock_code', models.CharField(blank=True, max_length=6)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFAMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('EMAIL', 'Código por correo'), ('SMS', 'Código por SMS'), ('TOTP', 'Aplicación OTP (TOTP)'), ('SECURITY_QUESTIONS', 'Preguntas secretas'), ('USB_KEY', 'Llave USB (YubiKey)')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_name', models.CharField(blank=True, max_length=128)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='mfa_method',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_question', to='accounts.mfamethod'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('session_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_device', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
    ]
