# Generated by Django 5.2.7 on 2025-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_securityquestion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessattempt',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
